"""Fonctions de calcul econometrique pures (hors IHM)."""

from .stats import (
    FarrarFTestResult,
    FarrarGlauberResult,
    FarrarGlobalResult,
    FarrarTTestResult,
    KleinTestResult,
    MulticollinearityResult,
    MulticollinearityVIFResult,
    OptimalMixResult,
    OutlierColumnResult,
    OutlierDetectionResult,
    PartialCorrelationResult,
    PartialCorrelationsFullResult,
    PartialR2Result,
    analyze_multicollinearity,
    calculate_partial_correlations,
    correct_outliers,
    detect_outliers,
    determine_optimal_mix,
    farrar_glauber_test,
    format_number,
    get_calculation_steps,
    get_french_summary,
    get_interpretations,
    get_model_formulas,
    klein_test,
)

__all__ = [
    # Dataclasses
    "OutlierColumnResult",
    "OutlierDetectionResult",
    "PartialCorrelationResult",
    "PartialR2Result",
    "PartialCorrelationsFullResult",
    "KleinTestResult",
    "FarrarGlobalResult",
    "FarrarFTestResult",
    "FarrarTTestResult",
    "FarrarGlauberResult",
    "OptimalMixResult",
    "MulticollinearityVIFResult",
    "MulticollinearityResult",
    # Functions
    "format_number",
    "detect_outliers",
    "correct_outliers",
    "calculate_partial_correlations",
    "klein_test",
    "farrar_glauber_test",
    "determine_optimal_mix",
    "analyze_multicollinearity",
    "get_french_summary",
    "get_model_formulas",
    "get_interpretations",
    "get_calculation_steps",
]
